services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    restart: unless-stopped
    ports:
      - "127.0.0.1:8888:8080"
    environment:
      - SEARXNG_INSTANCE_NAME=local
      - SEARXNG_HOSTNAME=localhost
      - SEARXNG_PORT=8080
    volumes:
      - ./searxng:/etc/searxng
