name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint-and-smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install JS deps
        run: |
          npm --version
          # No dependencies yet; keep step to allow future installs
          echo 'no deps'

      - name: Lint JS
        run: npm run lint

      - name: Run rooms smoke
        run: npm run smoke:rooms
      - name: Run memory smoke
        run: npm run smoke:memory

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff black

      - name: Lint Python
        run: npm run py:lint

      - name: Format check Python
        run: black --check gateway/tools
